###############################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: kappnav.operator.kappnav.io/v1
kind: Kappnav
metadata:
  name: kappnav
spec:

  ###############################################################################
  ## kAppNav REST API variables
  ###############################################################################

  appNavAPI:
    repository: mrglavas/kappnav-apis
    tag: 0.9.0-beta
    
  ###############################################################################
  ## kAppNav Controller variables
  ###############################################################################

  appNavController:
    repository: mrglavas/kappnav-controller
    tag: 0.9.0-beta
    
  ###############################################################################
  ## kAppNav UI variables
  ###############################################################################

  appNavUI:
    repository: mrglavas/kappnav-ui
    tag: 0.9.0-beta

  ###############################################################################
  ## kAppNav Inventory variables
  ###############################################################################

  extensionContainers: 
    appNavInv: 
      repository: mrglavas/kappnav-inv
      tag: 0.9.0-beta

  ###############################################################################
  ## Environmental variables
  ###############################################################################
  env:
    kubeEnv: okd
