###############################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappnav-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kappnav-operator
  template:
    metadata:
      labels:
        name: kappnav-operator
    spec:
      serviceAccountName: kappnav-operator
      containers:
        - name: kappnav-operator
          # Replace this with the built image name
          image: kappnav/operator:0.8.0
          command:
          - kappnav-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kappnav-operator"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kappnav-operator
subjects:
- kind: ServiceAccount
  name: kappnav-operator
  namespace: kappnav
roleRef:
  kind: ClusterRole
  name: kappnav-operator
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kappnav-operator
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kappnav-operator
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kappnavs.kappnav.operator.kappnav.io
spec:
  group: kappnav.operator.kappnav.io
  names:
    kind: Kappnav
    listKind: KappnavList
    plural: kappnavs
    singular: kappnav
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
