// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/kappnav/v1.Kappnav":       schema_pkg_apis_kappnav_v1_Kappnav(ref),
		"./pkg/apis/kappnav/v1.KappnavSpec":   schema_pkg_apis_kappnav_v1_KappnavSpec(ref),
		"./pkg/apis/kappnav/v1.KappnavStatus": schema_pkg_apis_kappnav_v1_KappnavStatus(ref),
	}
}

func schema_pkg_apis_kappnav_v1_Kappnav(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Kappnav is the Schema for the kappnavs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.KappnavSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.KappnavStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kappnav/v1.KappnavSpec", "./pkg/apis/kappnav/v1.KappnavStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kappnav_v1_KappnavSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KappnavSpec defines the desired state of Kappnav",
				Properties: map[string]spec.Schema{
					"appNavAPI": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.KappnavContainerConfiguration"),
						},
					},
					"appNavController": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.KappnavContainerConfiguration"),
						},
					},
					"appNavUI": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.KappnavContainerConfiguration"),
						},
					},
					"extensionContainers": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("./pkg/apis/kappnav/v1.KappnavContainerConfiguration"),
									},
								},
							},
						},
					},
					"image": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.KappnavImageConfiguration"),
						},
					},
					"env": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kappnav/v1.Environment"),
						},
					},
					"logging": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kappnav/v1.Environment", "./pkg/apis/kappnav/v1.KappnavContainerConfiguration", "./pkg/apis/kappnav/v1.KappnavImageConfiguration"},
	}
}

func schema_pkg_apis_kappnav_v1_KappnavStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KappnavStatus defines the observed state of Kappnav",
				Properties: map[string]spec.Schema{
					"conditions": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("./pkg/apis/kappnav/v1.StatusCondition"),
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kappnav/v1.StatusCondition"},
	}
}
